---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/data/authors.json
  label: Authors Data
- type: directory
  path: src/data/authors
  label: Authors
  create: documents
  match: "*"
  templates:
  - author
- type: directory
  path: src/pages/post
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:14
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
